### ISSUE TITLE
District name field too short

### ISSUE THREAD

**Issue by willbreitkreutz** [USACE/usace_master_data#2]
https://github.com/USACE/usace-master-data/blob/79fa3cfc99d23dcb853314510015e785948ddce8/engineer_reporting_organizations/postgres/create_districts.sql#L5

varchar 30 for district name is too short for transatlantic exp... district.  recommend using the column type of `text` rather than a pre-defined varchar with length.

**Comment by willbreitkreutz** [comment]
@charles-p-howe ping so you see this

**Comment by charles-p-howe** [comment]
Have updated column defs, and fixed the division script under the postgres directory.
